version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - test
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    networks:
      - test

networks:
  test:
    driver: bridge
